// Code generated by ent, DO NOT EDIT.

package userdevice

const (
	// Label holds the string label denoting the userdevice type in the database.
	Label = "user_device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldLatestSkipUpdate holds the string denoting the latest_skip_update field in the database.
	FieldLatestSkipUpdate = "latest_skip_update"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// Table holds the table name of the userdevice in the database.
	Table = "user_devices"
)

// Columns holds all SQL columns for userdevice fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldVersion,
	FieldPlatform,
	FieldLatestSkipUpdate,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeviceID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
