# golangci-lint configuration
# For more information see: https://golangci-lint.run/

run:
  timeout: 5m
  go: '1.22'

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: myapp
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    go: '1.22'
  stylecheck:
    go: '1.22'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - ineffassign
    - gosimple
    - staticcheck
    - unused
    - misspell
    - prealloc
    - stylecheck
  disable-all: false

issues:
  exclude-dirs:
    - mocks
    - ent
  exclude-files:
    - ".*_test.go"
    - "wire_gen.go"
  exclude-rules:
    - path: "ent/"
      linters:
        - all
    - path: "mocks/"
      linters:
        - all
    - text: "by other packages, and that will cause a test failure"
      linters:
        - staticcheck
