version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - makezero
    - nilerr
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - ifElseChain
        - hugeParam
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G101
        - G115
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: unexported-return
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - errcheck
          - gosec
          - unparam
        path: _test\.go
    paths:
      - ent
      - mocks
      - cmd/docs
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
