application:
  version: 0.0.1
  port: 8080
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net

db.config:
  username: root
  password: MyRoot!23
  host: localhost
  port: 3306
  database: test_ent
