application:
  version: 0.0.1
  port: 8080
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net

db.config:
  username: root
  password:
  host: localhost
  port: 3306
  database: test_ent

db.config.dev: mysql://root:@localhost:3306/dev