application:
  version: 0.0.1
  port: 8080
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net
db.config:
  username: root
  password:
  host: localhost
  port: 3306
  database: test_ent
cache:
  config:
    ristretto:
      numCounters: 1000
      maxCost: 100
    redis:
      username: root
      password:
      DB: 0
      poolSize: 10
      host: 127.0.0.1
      port: 6379