// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package transaction

import (
	"myapp/ent"
)

// Injectors from tx_service_injector.go:

func InitializedTxService(dbClient *ent.Client) *TxService {
	txService := NewTxService(dbClient)
	return txService
}
