// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package transaction

import (
	"github.com/google/wire"
	"myapp/ent"
)

// Injectors from trx_service_injector.go:

func InitializedTxService(dbClient *ent.Client) *TrxServiceImpl {
	trxServiceImpl := NewTrxService(dbClient)
	return trxServiceImpl
}

// trx_service_injector.go:

var provider = wire.NewSet(
	NewTrxService, wire.Bind(new(TrxService), new(*TrxServiceImpl)),
)
