// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// SystemParameter holds the schema definition for the SystemParameter entity.
type SystemParameter struct {
	ent.Schema
}

// Mixin of the User.
func (SystemParameter) Mixin() []ent.Mixin {
	return []ent.Mixin{
		VersionMixin{},
		BaseFieldMixin{},
	}
}

// Fields of the SystemParameter.
func (SystemParameter) Fields() []ent.Field {
	return []ent.Field{
		field.String("key").NotEmpty().Unique(),
		field.String("value").NotEmpty(),
	}
}

// Edges of the SystemParameter.
func (SystemParameter) Edges() []ent.Edge {
	return nil
}

func (SystemParameter) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("key"),
		index.Fields("value"),
	}
}
