// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type UserDevice struct {
	ent.Schema
}

// Mixin of the User.
func (UserDevice) Mixin() []ent.Mixin {
	return []ent.Mixin{
		VersionMixin{},
		BaseFieldMixin{},
	}
}

func (UserDevice) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"),
		field.Uint64("user_id"),
		field.String("version"),
		field.String("platform"),
		field.String("device_id").Optional(),
	}
}
func (UserDevice) Edges() []ent.Edge {
	return nil
}
func (UserDevice) Annotations() []schema.Annotation {
	return nil
}
