// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"), field.String("name"), field.String("email").Optional().Unique(), field.Bool("is_verified"), field.Time("email_verified_at").Optional(), field.String("password").Optional(), field.String("remember_token").Optional(), field.String("social_media_id").Optional(), field.String("avatar"), field.Time("created_at").Optional(), field.Time("updated_at").Optional(), field.Int32("role_id"), field.String("login_type").Optional(), field.String("sub_specialist").Optional(), field.String("firebase_token").Optional(), field.String("info").Optional(), field.String("description").Optional(), field.String("specialist").Optional(), field.String("phone").Optional().Unique(), field.Time("last_access_at"), field.Bool("pregnancy_mode"), field.Time("deleted_at").Optional(), field.Time("latest_skip_update").Optional(), field.Time("latest_deleted_at").Optional()}
}
func (User) Edges() []ent.Edge {
	return nil
}
func (User) Annotations() []schema.Annotation {
	return nil
}
