// Code generated by ent, DO NOT EDIT.

package atlasschemarevision

const (
	// Label holds the string label denoting the atlasschemarevision type in the database.
	Label = "atlas_schema_revision"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "version"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldApplied holds the string denoting the applied field in the database.
	FieldApplied = "applied"
	// FieldTotal holds the string denoting the total field in the database.
	FieldTotal = "total"
	// FieldExecutedAt holds the string denoting the executed_at field in the database.
	FieldExecutedAt = "executed_at"
	// FieldExecutionTime holds the string denoting the execution_time field in the database.
	FieldExecutionTime = "execution_time"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldErrorStmt holds the string denoting the error_stmt field in the database.
	FieldErrorStmt = "error_stmt"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldPartialHashes holds the string denoting the partial_hashes field in the database.
	FieldPartialHashes = "partial_hashes"
	// FieldOperatorVersion holds the string denoting the operator_version field in the database.
	FieldOperatorVersion = "operator_version"
	// Table holds the table name of the atlasschemarevision in the database.
	Table = "atlas_schema_revisions"
)

// Columns holds all SQL columns for atlasschemarevision fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldType,
	FieldApplied,
	FieldTotal,
	FieldExecutedAt,
	FieldExecutionTime,
	FieldError,
	FieldErrorStmt,
	FieldHash,
	FieldPartialHashes,
	FieldOperatorVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
