// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"myapp/ent/predicate"
	"myapp/ent/systemparameter"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemParameterDelete is the builder for deleting a SystemParameter entity.
type SystemParameterDelete struct {
	config
	hooks    []Hook
	mutation *SystemParameterMutation
}

// Where appends a list predicates to the SystemParameterDelete builder.
func (spd *SystemParameterDelete) Where(ps ...predicate.SystemParameter) *SystemParameterDelete {
	spd.mutation.Where(ps...)
	return spd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (spd *SystemParameterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, spd.sqlExec, spd.mutation, spd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (spd *SystemParameterDelete) ExecX(ctx context.Context) int {
	n, err := spd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (spd *SystemParameterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(systemparameter.Table, sqlgraph.NewFieldSpec(systemparameter.FieldID, field.TypeInt))
	if ps := spd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, spd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	spd.mutation.done = true
	return affected, err
}

// SystemParameterDeleteOne is the builder for deleting a single SystemParameter entity.
type SystemParameterDeleteOne struct {
	spd *SystemParameterDelete
}

// Where appends a list predicates to the SystemParameterDelete builder.
func (spdo *SystemParameterDeleteOne) Where(ps ...predicate.SystemParameter) *SystemParameterDeleteOne {
	spdo.spd.mutation.Where(ps...)
	return spdo
}

// Exec executes the deletion query.
func (spdo *SystemParameterDeleteOne) Exec(ctx context.Context) error {
	n, err := spdo.spd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{systemparameter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (spdo *SystemParameterDeleteOne) ExecX(ctx context.Context) {
	if err := spdo.Exec(ctx); err != nil {
		panic(err)
	}
}
