// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cache

import (
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
)

// Injectors from caching_service_injector.go:

func InitializedCachingServiceImpl(redisClient *redis.Client) *CachingServiceImpl {
	cachingServiceImpl := NewCachingServiceImpl(redisClient)
	return cachingServiceImpl
}

// caching_service_injector.go:

var provider = wire.NewSet(
	NewCachingServiceImpl, wire.Bind(new(CachingService), new(*CachingServiceImpl)),
)
