// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldIsVerified holds the string denoting the is_verified field in the database.
	FieldIsVerified = "is_verified"
	// FieldEmailVerifiedAt holds the string denoting the email_verified_at field in the database.
	FieldEmailVerifiedAt = "email_verified_at"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldRememberToken holds the string denoting the remember_token field in the database.
	FieldRememberToken = "remember_token"
	// FieldSocialMediaID holds the string denoting the social_media_id field in the database.
	FieldSocialMediaID = "social_media_id"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldLoginType holds the string denoting the login_type field in the database.
	FieldLoginType = "login_type"
	// FieldSubSpecialist holds the string denoting the sub_specialist field in the database.
	FieldSubSpecialist = "sub_specialist"
	// FieldFirebaseToken holds the string denoting the firebase_token field in the database.
	FieldFirebaseToken = "firebase_token"
	// FieldInfo holds the string denoting the info field in the database.
	FieldInfo = "info"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSpecialist holds the string denoting the specialist field in the database.
	FieldSpecialist = "specialist"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldLastAccessAt holds the string denoting the last_access_at field in the database.
	FieldLastAccessAt = "last_access_at"
	// FieldPregnancyMode holds the string denoting the pregnancy_mode field in the database.
	FieldPregnancyMode = "pregnancy_mode"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldLatestSkipUpdate holds the string denoting the latest_skip_update field in the database.
	FieldLatestSkipUpdate = "latest_skip_update"
	// FieldLatestDeletedAt holds the string denoting the latest_deleted_at field in the database.
	FieldLatestDeletedAt = "latest_deleted_at"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldIsVerified,
	FieldEmailVerifiedAt,
	FieldPassword,
	FieldRememberToken,
	FieldSocialMediaID,
	FieldAvatar,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRoleID,
	FieldLoginType,
	FieldSubSpecialist,
	FieldFirebaseToken,
	FieldInfo,
	FieldDescription,
	FieldSpecialist,
	FieldPhone,
	FieldLastAccessAt,
	FieldPregnancyMode,
	FieldDeletedAt,
	FieldLatestSkipUpdate,
	FieldLatestDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
