// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// System_parameter is the predicate function for system_parameter builders.
type System_parameter func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
