// ErrorCode generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// System_parameter is the predicate function for system_parameter builders.
type System_parameter func(*sql.Selector)
